/* eslint-disable @next/next/no-img-element */
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import TransWrap from "../Components/TransWrap";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransWrap>
        <img
          draggable={false}
          style={{ width: "100%", height: "100%" }}
          src="/test.png"
          alt="asd"
        />
      </TransWrap>
    </div>
  );
};

export default Home;
